sonar.organization=duracell04
sonar.projectKey=duracell04_sopra-fs26-group-42-client

# relative paths to source directories. More details and properties are described
# at https://docs.sonarsource.com/sonarqube-cloud/advanced-setup/analysis-scope/
sonar.sources=app
